import type { BrandTokens, BrandPayload } from "@ai-builder/ds-types";

/**
 * Map abstract BrandTokens to CivicTheme SCSS variables.
 *
 * CivicTheme requires SCSS compilation for branding — runtime CSS vars
 * are NOT supported. The output is an SCSS variables file that must be
 * compiled by the CivicTheme build pipeline.
 */
export function prepareBrandPayload(tokens: BrandTokens): BrandPayload {
  const primary = tokens.colors.primary;
  const secondary = tokens.colors.secondary;
  const accent = tokens.colors.accent ?? primary;
  const neutral = tokens.colors.neutral ?? "#6b7280";
  const background = tokens.colors.background ?? "#ffffff";
  const headingFont = tokens.fonts.heading ?? "'Lexend', sans-serif";
  const bodyFont = tokens.fonts.body ?? "'Inter', sans-serif";

  const scss = [
    "//",
    "// CivicTheme brand variables — generated by AI Builder",
    "// DO NOT EDIT MANUALLY — regenerated on each brand update.",
    "//",
    "",
    "// Brand colors",
    `$ct-color-primary: ${primary};`,
    `$ct-color-secondary: ${secondary};`,
    `$ct-color-accent: ${accent};`,
    `$ct-color-neutral: ${neutral};`,
    `$ct-color-background: ${background};`,
    "",
    "// Light theme palette",
    `$ct-light-background: ${background};`,
    `$ct-light-heading-color: #1a1a2e;`,
    `$ct-light-body-color: #333333;`,
    `$ct-light-border-color: #e5e7eb;`,
    `$ct-light-link-color: ${primary};`,
    `$ct-light-link-hover-color: ${secondary};`,
    "",
    "// Dark theme palette",
    `$ct-dark-background: #1a1a2e;`,
    `$ct-dark-heading-color: #ffffff;`,
    `$ct-dark-body-color: #e5e7eb;`,
    `$ct-dark-border-color: #374151;`,
    `$ct-dark-link-color: ${accent};`,
    `$ct-dark-link-hover-color: ${primary};`,
    "",
    "// Typography",
    `$ct-font-heading: ${headingFont};`,
    `$ct-font-body: ${bodyFont};`,
    "",
    "// Button colors",
    `$ct-button-primary-bg: ${primary};`,
    `$ct-button-primary-hover-bg: ${secondary};`,
    `$ct-button-secondary-bg: transparent;`,
    `$ct-button-secondary-border: ${primary};`,
    `$ct-button-secondary-color: ${primary};`,
    "",
  ].join("\n");

  return {
    type: "scss-file",
    path: "web/themes/custom/civictheme_starter/components/_variables.base.scss",
    content: scss,
    requiresBuild: true,
  };
}
